package com.example.assignment.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.ACCOUNT_ID
     *
     * @mbg.generated Thu Sep 12 19:52:16 CST 2019
     */
    private String accountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.ACCOUNT_ID
     *
     * @return the value of ADMIN.ACCOUNT_ID
     *
     * @mbg.generated Thu Sep 12 19:52:16 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.ACCOUNT_ID
     *
     * @param accountId the value for ADMIN.ACCOUNT_ID
     *
     * @mbg.generated Thu Sep 12 19:52:16 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }
}