package com.example.assignment.mapper;

import com.example.assignment.model.Like;
import com.example.assignment.model.LikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    long countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    List<Like> selectByExampleWithRowbounds(LikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIKES
     *
     * @mbg.generated Wed Sep 11 13:56:46 CST 2019
     */
    int updateByExample(@Param("record") Like record, @Param("example") LikeExample example);
}